import type { Verb, Word } from "../types";

export const SAMPLE_WORDS: Word[] = [
	{
		id: "1",
		word: "apple",
		translation: "яблоко",
		difficulty: "easy",
		partOfSpeech: "noun",
		example: "I eat an apple every day.",
	},
	{
		id: "2",
		word: "beautiful",
		translation: "красивый",
		difficulty: "easy",
		partOfSpeech: "adjective",
		example: "The sunset is beautiful.",
	},
	{
		id: "3",
		word: "challenge",
		translation: "вызов, сложная задача",
		difficulty: "medium",
		partOfSpeech: "noun",
		example: "Learning a new language is a challenge.",
	},
	{
		id: "4",
		word: "develop",
		translation: "развивать",
		difficulty: "medium",
		partOfSpeech: "verb",
		example: "We need to develop new skills.",
	},
	{
		id: "5",
		word: "encourage",
		translation: "поощрять, воодушевлять",
		difficulty: "medium",
		partOfSpeech: "verb",
		example: "Teachers encourage students to ask questions.",
	},
	{
		id: "6",
		word: "fascinating",
		translation: "увлекательный, захватывающий",
		difficulty: "hard",
		partOfSpeech: "adjective",
		example: "The documentary was fascinating.",
	},
	{
		id: "7",
		word: "generous",
		translation: "щедрый",
		difficulty: "medium",
		partOfSpeech: "adjective",
		example: "She is very generous with her time.",
	},
	{
		id: "8",
		word: "hesitate",
		translation: "колебаться, сомневаться",
		difficulty: "hard",
		partOfSpeech: "verb",
		example: "Don't hesitate to ask for help.",
	},
	{
		id: "9",
		word: "important",
		translation: "важный",
		difficulty: "easy",
		partOfSpeech: "adjective",
		example: "This is an important decision.",
	},
	{
		id: "10",
		word: "journey",
		translation: "путешествие, поездка",
		difficulty: "medium",
		partOfSpeech: "noun",
		example: "Life is a journey, not a destination.",
	},
	{
		id: "11",
		word: "knowledge",
		translation: "знание",
		difficulty: "medium",
		partOfSpeech: "noun",
		example: "Knowledge is power.",
	},
	{
		id: "12",
		word: "lazy",
		translation: "ленивый",
		difficulty: "easy",
		partOfSpeech: "adjective",
		example: "Don't be lazy, start working!",
	},
	{
		id: "13",
		word: "magnificent",
		translation: "великолепный",
		difficulty: "hard",
		partOfSpeech: "adjective",
		example: "The palace was magnificent.",
	},
	{
		id: "14",
		word: "necessary",
		translation: "необходимый",
		difficulty: "medium",
		partOfSpeech: "adjective",
		example: "Sleep is necessary for health.",
	},
	{
		id: "15",
		word: "obvious",
		translation: "очевидный",
		difficulty: "medium",
		partOfSpeech: "adjective",
		example: "The answer is obvious.",
	},
	{
		id: "16",
		word: "patient",
		translation: "терпеливый",
		difficulty: "medium",
		partOfSpeech: "adjective",
		example: "Be patient with yourself.",
	},
	{
		id: "17",
		word: "quality",
		translation: "качество",
		difficulty: "easy",
		partOfSpeech: "noun",
		example: "Quality is more important than quantity.",
	},
	{
		id: "18",
		word: "remember",
		translation: "помнить",
		difficulty: "easy",
		partOfSpeech: "verb",
		example: "I remember our first meeting.",
	},
	{
		id: "19",
		word: "succeed",
		translation: "преуспеть, добиться успеха",
		difficulty: "medium",
		partOfSpeech: "verb",
		example: "You will succeed if you work hard.",
	},
	{
		id: "20",
		word: "treasure",
		translation: "сокровище, ценить",
		difficulty: "medium",
		partOfSpeech: "noun/verb",
		example: "Friendship is a treasure.",
	},
	{
		id: "21",
		word: "understand",
		translation: "понимать",
		difficulty: "easy",
		partOfSpeech: "verb",
		example: "I understand your point of view.",
	},
	{
		id: "22",
		word: "valuable",
		translation: "ценный",
		difficulty: "medium",
		partOfSpeech: "adjective",
		example: "Your advice is very valuable.",
	},
	{
		id: "23",
		word: "wisdom",
		translation: "мудрость",
		difficulty: "medium",
		partOfSpeech: "noun",
		example: "With age comes wisdom.",
	},
	{
		id: "24",
		word: "achieve",
		translation: "достигать",
		difficulty: "medium",
		partOfSpeech: "verb",
		example: "You can achieve anything you set your mind to.",
	},
	{
		id: "25",
		word: "benefit",
		translation: "польза, выгода",
		difficulty: "medium",
		partOfSpeech: "noun",
		example: "Exercise has many health benefits.",
	},
];

export const SAMPLE_VERBS: Verb[] = [
	{
		id: "v1",
		base: "be",
		past: "was/were",
		participle: "been",
		translation: "быть",
		difficulty: "easy",
		examples: ["I am happy", "He was here", "They have been waiting"],
	},
	{
		id: "v2",
		base: "go",
		past: "went",
		participle: "gone/been",
		translation: "идти, ехать",
		difficulty: "easy",
		examples: ["I go to school", "She went home", "They have gone shopping"],
	},
	{
		id: "v3",
		base: "have",
		past: "had",
		participle: "had",
		translation: "иметь",
		difficulty: "easy",
		examples: ["I have a car", "She had lunch", "We have had this talk before"],
	},
	{
		id: "v4",
		base: "do",
		past: "did",
		participle: "done",
		translation: "делать",
		difficulty: "easy",
		examples: [
			"I do my homework",
			"He did his best",
			"We have done everything",
		],
	},
	{
		id: "v5",
		base: "say",
		past: "said",
		participle: "said",
		translation: "говорить, сказать",
		difficulty: "easy",
		examples: ["I say hello", "She said goodbye", "They have said nothing"],
	},
	{
		id: "v6",
		base: "get",
		past: "got",
		participle: "got/gotten",
		translation: "получать",
		difficulty: "easy",
		examples: ["I get up early", "He got a gift", "We have gotten lost"],
	},
	{
		id: "v7",
		base: "make",
		past: "made",
		participle: "made",
		translation: "делать, создавать",
		difficulty: "easy",
		examples: [
			"I make breakfast",
			"She made a cake",
			"They have made a decision",
		],
	},
	{
		id: "v8",
		base: "know",
		past: "knew",
		participle: "known",
		translation: "знать",
		difficulty: "easy",
		examples: [
			"I know the answer",
			"He knew the truth",
			"We have known each other",
		],
	},
	{
		id: "v9",
		base: "think",
		past: "thought",
		participle: "thought",
		translation: "думать",
		difficulty: "easy",
		examples: [
			"I think so",
			"She thought about it",
			"They have thought it through",
		],
	},
	{
		id: "v10",
		base: "see",
		past: "saw",
		participle: "seen",
		translation: "видеть",
		difficulty: "easy",
		examples: ["I see you", "He saw a movie", "We have seen this before"],
	},
	{
		id: "v11",
		base: "come",
		past: "came",
		participle: "come",
		translation: "приходить",
		difficulty: "easy",
		examples: [
			"I come here often",
			"She came yesterday",
			"They have come early",
		],
	},
	{
		id: "v12",
		base: "take",
		past: "took",
		participle: "taken",
		translation: "брать, взять",
		difficulty: "easy",
		examples: ["I take the bus", "He took a photo", "We have taken notes"],
	},
	{
		id: "v13",
		base: "give",
		past: "gave",
		participle: "given",
		translation: "давать",
		difficulty: "easy",
		examples: ["I give advice", "She gave a gift", "They have given up"],
	},
	{
		id: "v14",
		base: "find",
		past: "found",
		participle: "found",
		translation: "находить",
		difficulty: "easy",
		examples: [
			"I find it easy",
			"He found his keys",
			"We have found a solution",
		],
	},
	{
		id: "v15",
		base: "tell",
		past: "told",
		participle: "told",
		translation: "рассказывать, сказать",
		difficulty: "easy",
		examples: [
			"I tell stories",
			"She told the truth",
			"They have told me everything",
		],
	},
	{
		id: "v16",
		base: "write",
		past: "wrote",
		participle: "written",
		translation: "писать",
		difficulty: "medium",
		examples: ["I write emails", "He wrote a book", "We have written a letter"],
	},
	{
		id: "v17",
		base: "speak",
		past: "spoke",
		participle: "spoken",
		translation: "говорить",
		difficulty: "medium",
		examples: [
			"I speak English",
			"She spoke loudly",
			"They have spoken to the manager",
		],
	},
	{
		id: "v18",
		base: "read",
		past: "read",
		participle: "read",
		translation: "читать",
		difficulty: "medium",
		examples: ["I read books", "He read the news", "We have read this article"],
	},
	{
		id: "v19",
		base: "buy",
		past: "bought",
		participle: "bought",
		translation: "покупать",
		difficulty: "easy",
		examples: [
			"I buy groceries",
			"She bought a car",
			"They have bought tickets",
		],
	},
	{
		id: "v20",
		base: "begin",
		past: "began",
		participle: "begun",
		translation: "начинать",
		difficulty: "medium",
		examples: [
			"I begin work at 9",
			"He began studying",
			"We have begun the project",
		],
	},
	{
		id: "v21",
		base: "break",
		past: "broke",
		participle: "broken",
		translation: "ломать",
		difficulty: "medium",
		examples: [
			"I break eggs for breakfast",
			"She broke the vase",
			"They have broken the record",
		],
	},
	{
		id: "v22",
		base: "bring",
		past: "brought",
		participle: "brought",
		translation: "приносить",
		difficulty: "easy",
		examples: ["I bring lunch", "He brought flowers", "We have brought gifts"],
	},
	{
		id: "v23",
		base: "build",
		past: "built",
		participle: "built",
		translation: "строить",
		difficulty: "medium",
		examples: ["I build models", "She built a house", "They have built trust"],
	},
	{
		id: "v24",
		base: "catch",
		past: "caught",
		participle: "caught",
		translation: "ловить",
		difficulty: "medium",
		examples: [
			"I catch the ball",
			"He caught a cold",
			"We have caught the train",
		],
	},
	{
		id: "v25",
		base: "choose",
		past: "chose",
		participle: "chosen",
		translation: "выбирать",
		difficulty: "medium",
		examples: [
			"I choose wisely",
			"She chose the red dress",
			"They have chosen a leader",
		],
	},
	{
		id: "v26",
		base: "draw",
		past: "drew",
		participle: "drawn",
		translation: "рисовать",
		difficulty: "medium",
		examples: ["I draw pictures", "He drew a map", "We have drawn conclusions"],
	},
	{
		id: "v27",
		base: "drink",
		past: "drank",
		participle: "drunk",
		translation: "пить",
		difficulty: "easy",
		examples: [
			"I drink water",
			"She drank coffee",
			"They have drunk all the juice",
		],
	},
	{
		id: "v28",
		base: "drive",
		past: "drove",
		participle: "driven",
		translation: "водить (машину)",
		difficulty: "easy",
		examples: [
			"I drive to work",
			"He drove carefully",
			"We have driven for hours",
		],
	},
	{
		id: "v29",
		base: "eat",
		past: "ate",
		participle: "eaten",
		translation: "есть",
		difficulty: "easy",
		examples: ["I eat healthy", "She ate breakfast", "They have eaten already"],
	},
	{
		id: "v30",
		base: "fall",
		past: "fell",
		participle: "fallen",
		translation: "падать",
		difficulty: "medium",
		examples: [
			"I fall asleep quickly",
			"He fell down",
			"We have fallen behind",
		],
	},
	{
		id: "v31",
		base: "beat",
		past: "beat",
		participle: "beaten",
		translation: "бить, побеждать",
		difficulty: "medium",
		examples: [
			"I beat the rhythm",
			"He beat his opponent",
			"They have beaten the record",
		],
	},
	{
		id: "v32",
		base: "become",
		past: "became",
		participle: "become",
		translation: "становиться",
		difficulty: "easy",
		examples: [
			"I become tired easily",
			"She became a doctor",
			"They have become successful",
		],
	},
	{
		id: "v33",
		base: "blow",
		past: "blew",
		participle: "blown",
		translation: "дуть",
		difficulty: "medium",
		examples: [
			"I blow bubbles",
			"She blew out the candles",
			"The wind has blown all day",
		],
	},
	{
		id: "v34",
		base: "burn",
		past: "burnt",
		participle: "burnt",
		translation: "гореть, жечь",
		difficulty: "medium",
		examples: [
			"I burn wood in winter",
			"She burnt the toast",
			"They have burnt the old documents",
		],
	},
	{
		id: "v35",
		base: "cost",
		past: "cost",
		participle: "cost",
		translation: "стоить",
		difficulty: "easy",
		examples: [
			"Tickets cost $50",
			"It cost too much",
			"This mistake has cost us dearly",
		],
	},
	{
		id: "v36",
		base: "cut",
		past: "cut",
		participle: "cut",
		translation: "резать",
		difficulty: "easy",
		examples: [
			"I cut vegetables",
			"She cut her hair",
			"They have cut the budget",
		],
	},
	{
		id: "v37",
		base: "feel",
		past: "felt",
		participle: "felt",
		translation: "чувствовать",
		difficulty: "easy",
		examples: [
			"I feel happy today",
			"He felt sick yesterday",
			"We have felt this way before",
		],
	},
	{
		id: "v38",
		base: "fly",
		past: "flew",
		participle: "flown",
		translation: "летать",
		difficulty: "easy",
		examples: [
			"I fly often for work",
			"She flew to Paris",
			"They have flown first class",
		],
	},
	{
		id: "v39",
		base: "forget",
		past: "forgot",
		participle: "forgotten",
		translation: "забывать",
		difficulty: "medium",
		examples: [
			"I forget names easily",
			"He forgot his password",
			"We have forgotten the address",
		],
	},
	{
		id: "v40",
		base: "grow",
		past: "grew",
		participle: "grown",
		translation: "расти",
		difficulty: "easy",
		examples: [
			"I grow vegetables",
			"She grew up in London",
			"They have grown taller",
		],
	},
	{
		id: "v41",
		base: "hear",
		past: "heard",
		participle: "heard",
		translation: "слышать",
		difficulty: "easy",
		examples: ["I hear music", "He heard the news", "We have heard the rumors"],
	},
	{
		id: "v42",
		base: "hide",
		past: "hid",
		participle: "hidden",
		translation: "прятать",
		difficulty: "medium",
		examples: [
			"I hide my diary",
			"She hid the presents",
			"They have hidden the treasure",
		],
	},
	{
		id: "v43",
		base: "hit",
		past: "hit",
		participle: "hit",
		translation: "ударять, бить",
		difficulty: "easy",
		examples: ["I hit the ball", "He hit the target", "We have hit a problem"],
	},
	{
		id: "v44",
		base: "hold",
		past: "held",
		participle: "held",
		translation: "держать",
		difficulty: "easy",
		examples: [
			"I hold your hand",
			"She held the baby",
			"They have held this view",
		],
	},
	{
		id: "v45",
		base: "hurt",
		past: "hurt",
		participle: "hurt",
		translation: "ранить, причинять боль",
		difficulty: "easy",
		examples: ["I hurt my leg", "It hurt a lot", "They have hurt his feelings"],
	},
	{
		id: "v46",
		base: "keep",
		past: "kept",
		participle: "kept",
		translation: "хранить, держать",
		difficulty: "easy",
		examples: [
			"I keep a diary",
			"She kept the secret",
			"We have kept in touch",
		],
	},
	{
		id: "v47",
		base: "learn",
		past: "learnt/learned",
		participle: "learnt/learned",
		translation: "учить, изучать",
		difficulty: "easy",
		examples: [
			"I learn English",
			"He learnt to swim",
			"They have learned the lesson",
		],
	},
	{
		id: "v48",
		base: "leave",
		past: "left",
		participle: "left",
		translation: "оставлять, уходить",
		difficulty: "easy",
		examples: [
			"I leave at 5 pm",
			"She left her keys",
			"They have left the building",
		],
	},
	{
		id: "v49",
		base: "lend",
		past: "lent",
		participle: "lent",
		translation: "одалживать",
		difficulty: "medium",
		examples: [
			"I lend books to friends",
			"He lent me money",
			"We have lent our car",
		],
	},
	{
		id: "v50",
		base: "let",
		past: "let",
		participle: "let",
		translation: "позволять, разрешать",
		difficulty: "easy",
		examples: ["I let him go", "She let me borrow it", "They have let us stay"],
	},
	{
		id: "v51",
		base: "lose",
		past: "lost",
		participle: "lost",
		translation: "терять",
		difficulty: "easy",
		examples: [
			"I lose my keys often",
			"He lost the game",
			"We have lost our way",
		],
	},
	{
		id: "v52",
		base: "mean",
		past: "meant",
		participle: "meant",
		translation: "означать",
		difficulty: "medium",
		examples: [
			"I mean well",
			"She meant no harm",
			"They have meant everything to me",
		],
	},
	{
		id: "v53",
		base: "meet",
		past: "met",
		participle: "met",
		translation: "встречать",
		difficulty: "easy",
		examples: [
			"I meet friends daily",
			"He met her yesterday",
			"We have met before",
		],
	},
	{
		id: "v54",
		base: "pay",
		past: "paid",
		participle: "paid",
		translation: "платить",
		difficulty: "easy",
		examples: [
			"I pay bills online",
			"She paid cash",
			"They have paid the rent",
		],
	},
	{
		id: "v55",
		base: "put",
		past: "put",
		participle: "put",
		translation: "класть, ставить",
		difficulty: "easy",
		examples: [
			"I put books on the shelf",
			"He put it there",
			"We have put in effort",
		],
	},
	{
		id: "v56",
		base: "ring",
		past: "rang",
		participle: "rung",
		translation: "звонить",
		difficulty: "medium",
		examples: [
			"I ring the doorbell",
			"The phone rang loudly",
			"They have rung three times",
		],
	},
	{
		id: "v57",
		base: "run",
		past: "ran",
		participle: "run",
		translation: "бегать",
		difficulty: "easy",
		examples: [
			"I run every morning",
			"She ran a marathon",
			"They have run out of time",
		],
	},
	{
		id: "v58",
		base: "sell",
		past: "sold",
		participle: "sold",
		translation: "продавать",
		difficulty: "easy",
		examples: ["I sell antiques", "He sold his car", "We have sold everything"],
	},
	{
		id: "v59",
		base: "send",
		past: "sent",
		participle: "sent",
		translation: "отправлять",
		difficulty: "easy",
		examples: [
			"I send emails daily",
			"She sent a package",
			"They have sent invitations",
		],
	},
	{
		id: "v60",
		base: "show",
		past: "showed",
		participle: "shown",
		translation: "показывать",
		difficulty: "easy",
		examples: [
			"I show respect",
			"He showed me photos",
			"We have shown interest",
		],
	},
	{
		id: "v61",
		base: "shut",
		past: "shut",
		participle: "shut",
		translation: "закрывать",
		difficulty: "medium",
		examples: [
			"I shut the door quietly",
			"She shut the window",
			"They have shut down",
		],
	},
	{
		id: "v62",
		base: "sing",
		past: "sang",
		participle: "sung",
		translation: "петь",
		difficulty: "medium",
		examples: [
			"I sing in the shower",
			"He sang beautifully",
			"We have sung this song",
		],
	},
	{
		id: "v63",
		base: "sit",
		past: "sat",
		participle: "sat",
		translation: "сидеть",
		difficulty: "easy",
		examples: [
			"I sit at my desk",
			"She sat down slowly",
			"They have sat for hours",
		],
	},
	{
		id: "v64",
		base: "sleep",
		past: "slept",
		participle: "slept",
		translation: "спать",
		difficulty: "easy",
		examples: ["I sleep well", "He slept until noon", "We have slept enough"],
	},
	{
		id: "v65",
		base: "spend",
		past: "spent",
		participle: "spent",
		translation: "тратить",
		difficulty: "easy",
		examples: [
			"I spend time reading",
			"She spent all her money",
			"They have spent years here",
		],
	},
	{
		id: "v66",
		base: "stand",
		past: "stood",
		participle: "stood",
		translation: "стоять",
		difficulty: "easy",
		examples: [
			"I stand in line",
			"He stood up quickly",
			"We have stood here before",
		],
	},
	{
		id: "v67",
		base: "steal",
		past: "stole",
		participle: "stolen",
		translation: "красть",
		difficulty: "medium",
		examples: [
			"Thieves steal bikes",
			"Someone stole my wallet",
			"They have stolen jewels",
		],
	},
	{
		id: "v68",
		base: "sweep",
		past: "swept",
		participle: "swept",
		translation: "подметать",
		difficulty: "hard",
		examples: [
			"I sweep the floor daily",
			"She swept the leaves",
			"They have swept the porch",
		],
	},
	{
		id: "v69",
		base: "swim",
		past: "swam",
		participle: "swum",
		translation: "плавать",
		difficulty: "medium",
		examples: [
			"I swim every week",
			"He swam across the lake",
			"We have swum here before",
		],
	},
	{
		id: "v70",
		base: "teach",
		past: "taught",
		participle: "taught",
		translation: "учить, преподавать",
		difficulty: "easy",
		examples: [
			"I teach English",
			"She taught math",
			"They have taught for years",
		],
	},
	{
		id: "v71",
		base: "throw",
		past: "threw",
		participle: "thrown",
		translation: "бросать",
		difficulty: "medium",
		examples: [
			"I throw the ball",
			"He threw it away",
			"We have thrown a party",
		],
	},
	{
		id: "v72",
		base: "understand",
		past: "understood",
		participle: "understood",
		translation: "понимать",
		difficulty: "easy",
		examples: [
			"I understand you",
			"She understood the problem",
			"They have understood clearly",
		],
	},
	{
		id: "v73",
		base: "wake",
		past: "woke",
		participle: "woken",
		translation: "просыпаться",
		difficulty: "medium",
		examples: ["I wake at 7 am", "He woke up early", "We have woken the baby"],
	},
	{
		id: "v74",
		base: "wear",
		past: "wore",
		participle: "worn",
		translation: "носить (одежду)",
		difficulty: "easy",
		examples: ["I wear glasses", "She wore a dress", "They have worn uniforms"],
	},
	{
		id: "v75",
		base: "win",
		past: "won",
		participle: "won",
		translation: "выигрывать, побеждать",
		difficulty: "easy",
		examples: [
			"I win sometimes",
			"He won the race",
			"We have won the championship",
		],
	},
];

// Helper functions to get random words/verbs
export function getRandomWords(count: number): Word[] {
	const shuffled = [...SAMPLE_WORDS].sort(() => Math.random() - 0.5);
	return shuffled.slice(0, count);
}

export function getRandomVerbs(count: number): Verb[] {
	const shuffled = [...SAMPLE_VERBS].sort(() => Math.random() - 0.5);
	return shuffled.slice(0, count);
}

export function getRandomWrongAnswers(
	correctAnswer: string,
	allWords: Word[],
	count: number = 3,
): string[] {
	const wrongAnswers = allWords
		.filter((w) => w.translation !== correctAnswer)
		.map((w) => w.translation)
		.sort(() => Math.random() - 0.5)
		.slice(0, count);

	return wrongAnswers;
}
