import type { Verb, Word } from "../types";

export const SAMPLE_WORDS: Word[] = [
	{
		id: "1",
		word: "apple",
		translation: "яблоко",
		difficulty: "easy",
		partOfSpeech: "noun",
		example: "I eat an apple every day.",
	},
	{
		id: "2",
		word: "beautiful",
		translation: "красивый",
		difficulty: "easy",
		partOfSpeech: "adjective",
		example: "The sunset is beautiful.",
	},
	{
		id: "3",
		word: "challenge",
		translation: "вызов, сложная задача",
		difficulty: "medium",
		partOfSpeech: "noun",
		example: "Learning a new language is a challenge.",
	},
	{
		id: "4",
		word: "develop",
		translation: "развивать",
		difficulty: "medium",
		partOfSpeech: "verb",
		example: "We need to develop new skills.",
	},
	{
		id: "5",
		word: "encourage",
		translation: "поощрять, воодушевлять",
		difficulty: "medium",
		partOfSpeech: "verb",
		example: "Teachers encourage students to ask questions.",
	},
	{
		id: "6",
		word: "fascinating",
		translation: "увлекательный, захватывающий",
		difficulty: "hard",
		partOfSpeech: "adjective",
		example: "The documentary was fascinating.",
	},
	{
		id: "7",
		word: "generous",
		translation: "щедрый",
		difficulty: "medium",
		partOfSpeech: "adjective",
		example: "She is very generous with her time.",
	},
	{
		id: "8",
		word: "hesitate",
		translation: "колебаться, сомневаться",
		difficulty: "hard",
		partOfSpeech: "verb",
		example: "Don't hesitate to ask for help.",
	},
	{
		id: "9",
		word: "important",
		translation: "важный",
		difficulty: "easy",
		partOfSpeech: "adjective",
		example: "This is an important decision.",
	},
	{
		id: "10",
		word: "journey",
		translation: "путешествие, поездка",
		difficulty: "medium",
		partOfSpeech: "noun",
		example: "Life is a journey, not a destination.",
	},
	{
		id: "11",
		word: "knowledge",
		translation: "знание",
		difficulty: "medium",
		partOfSpeech: "noun",
		example: "Knowledge is power.",
	},
	{
		id: "12",
		word: "lazy",
		translation: "ленивый",
		difficulty: "easy",
		partOfSpeech: "adjective",
		example: "Don't be lazy, start working!",
	},
	{
		id: "13",
		word: "magnificent",
		translation: "великолепный",
		difficulty: "hard",
		partOfSpeech: "adjective",
		example: "The palace was magnificent.",
	},
	{
		id: "14",
		word: "necessary",
		translation: "необходимый",
		difficulty: "medium",
		partOfSpeech: "adjective",
		example: "Sleep is necessary for health.",
	},
	{
		id: "15",
		word: "obvious",
		translation: "очевидный",
		difficulty: "medium",
		partOfSpeech: "adjective",
		example: "The answer is obvious.",
	},
	{
		id: "16",
		word: "patient",
		translation: "терпеливый",
		difficulty: "medium",
		partOfSpeech: "adjective",
		example: "Be patient with yourself.",
	},
	{
		id: "17",
		word: "quality",
		translation: "качество",
		difficulty: "easy",
		partOfSpeech: "noun",
		example: "Quality is more important than quantity.",
	},
	{
		id: "18",
		word: "remember",
		translation: "помнить",
		difficulty: "easy",
		partOfSpeech: "verb",
		example: "I remember our first meeting.",
	},
	{
		id: "19",
		word: "succeed",
		translation: "преуспеть, добиться успеха",
		difficulty: "medium",
		partOfSpeech: "verb",
		example: "You will succeed if you work hard.",
	},
	{
		id: "20",
		word: "treasure",
		translation: "сокровище, ценить",
		difficulty: "medium",
		partOfSpeech: "noun/verb",
		example: "Friendship is a treasure.",
	},
	{
		id: "21",
		word: "understand",
		translation: "понимать",
		difficulty: "easy",
		partOfSpeech: "verb",
		example: "I understand your point of view.",
	},
	{
		id: "22",
		word: "valuable",
		translation: "ценный",
		difficulty: "medium",
		partOfSpeech: "adjective",
		example: "Your advice is very valuable.",
	},
	{
		id: "23",
		word: "wisdom",
		translation: "мудрость",
		difficulty: "medium",
		partOfSpeech: "noun",
		example: "With age comes wisdom.",
	},
	{
		id: "24",
		word: "achieve",
		translation: "достигать",
		difficulty: "medium",
		partOfSpeech: "verb",
		example: "You can achieve anything you set your mind to.",
	},
	{
		id: "25",
		word: "benefit",
		translation: "польза, выгода",
		difficulty: "medium",
		partOfSpeech: "noun",
		example: "Exercise has many health benefits.",
	},
];

export const SAMPLE_VERBS: Verb[] = [
	{
		id: "v1",
		base: "be",
		past: "was/were",
		participle: "been",
		translation: "быть",
		difficulty: "common",
		examples: ["I am happy", "He was here", "They have been waiting"],
	},
	{
		id: "v2",
		base: "go",
		past: "went",
		participle: "gone",
		translation: "идти, ехать",
		difficulty: "common",
		examples: ["I go to school", "She went home", "They have gone shopping"],
	},
	{
		id: "v3",
		base: "have",
		past: "had",
		participle: "had",
		translation: "иметь",
		difficulty: "common",
		examples: ["I have a car", "She had lunch", "We have had this talk before"],
	},
	{
		id: "v4",
		base: "do",
		past: "did",
		participle: "done",
		translation: "делать",
		difficulty: "common",
		examples: [
			"I do my homework",
			"He did his best",
			"We have done everything",
		],
	},
	{
		id: "v5",
		base: "say",
		past: "said",
		participle: "said",
		translation: "говорить, сказать",
		difficulty: "common",
		examples: ["I say hello", "She said goodbye", "They have said nothing"],
	},
	{
		id: "v6",
		base: "get",
		past: "got",
		participle: "got/gotten",
		translation: "получать",
		difficulty: "common",
		examples: ["I get up early", "He got a gift", "We have gotten lost"],
	},
	{
		id: "v7",
		base: "make",
		past: "made",
		participle: "made",
		translation: "делать, создавать",
		difficulty: "common",
		examples: [
			"I make breakfast",
			"She made a cake",
			"They have made a decision",
		],
	},
	{
		id: "v8",
		base: "know",
		past: "knew",
		participle: "known",
		translation: "знать",
		difficulty: "common",
		examples: [
			"I know the answer",
			"He knew the truth",
			"We have known each other",
		],
	},
	{
		id: "v9",
		base: "think",
		past: "thought",
		participle: "thought",
		translation: "думать",
		difficulty: "common",
		examples: [
			"I think so",
			"She thought about it",
			"They have thought it through",
		],
	},
	{
		id: "v10",
		base: "see",
		past: "saw",
		participle: "seen",
		translation: "видеть",
		difficulty: "common",
		examples: ["I see you", "He saw a movie", "We have seen this before"],
	},
	{
		id: "v11",
		base: "come",
		past: "came",
		participle: "come",
		translation: "приходить",
		difficulty: "common",
		examples: [
			"I come here often",
			"She came yesterday",
			"They have come early",
		],
	},
	{
		id: "v12",
		base: "take",
		past: "took",
		participle: "taken",
		translation: "брать, взять",
		difficulty: "common",
		examples: ["I take the bus", "He took a photo", "We have taken notes"],
	},
	{
		id: "v13",
		base: "give",
		past: "gave",
		participle: "given",
		translation: "давать",
		difficulty: "common",
		examples: ["I give advice", "She gave a gift", "They have given up"],
	},
	{
		id: "v14",
		base: "find",
		past: "found",
		participle: "found",
		translation: "находить",
		difficulty: "common",
		examples: [
			"I find it easy",
			"He found his keys",
			"We have found a solution",
		],
	},
	{
		id: "v15",
		base: "tell",
		past: "told",
		participle: "told",
		translation: "рассказывать, сказать",
		difficulty: "common",
		examples: [
			"I tell stories",
			"She told the truth",
			"They have told me everything",
		],
	},
	{
		id: "v16",
		base: "write",
		past: "wrote",
		participle: "written",
		translation: "писать",
		difficulty: "medium",
		examples: ["I write emails", "He wrote a book", "We have written a letter"],
	},
	{
		id: "v17",
		base: "speak",
		past: "spoke",
		participle: "spoken",
		translation: "говорить",
		difficulty: "medium",
		examples: [
			"I speak English",
			"She spoke loudly",
			"They have spoken to the manager",
		],
	},
	{
		id: "v18",
		base: "read",
		past: "read",
		participle: "read",
		translation: "читать",
		difficulty: "medium",
		examples: ["I read books", "He read the news", "We have read this article"],
	},
	{
		id: "v19",
		base: "buy",
		past: "bought",
		participle: "bought",
		translation: "покупать",
		difficulty: "medium",
		examples: [
			"I buy groceries",
			"She bought a car",
			"They have bought tickets",
		],
	},
	{
		id: "v20",
		base: "begin",
		past: "began",
		participle: "begun",
		translation: "начинать",
		difficulty: "medium",
		examples: [
			"I begin work at 9",
			"He began studying",
			"We have begun the project",
		],
	},
	{
		id: "v21",
		base: "break",
		past: "broke",
		participle: "broken",
		translation: "ломать",
		difficulty: "medium",
		examples: [
			"I break the rules",
			"She broke the vase",
			"They have broken up",
		],
	},
	{
		id: "v22",
		base: "bring",
		past: "brought",
		participle: "brought",
		translation: "приносить",
		difficulty: "medium",
		examples: ["I bring lunch", "He brought flowers", "We have brought gifts"],
	},
	{
		id: "v23",
		base: "build",
		past: "built",
		participle: "built",
		translation: "строить",
		difficulty: "medium",
		examples: ["I build models", "She built a house", "They have built trust"],
	},
	{
		id: "v24",
		base: "catch",
		past: "caught",
		participle: "caught",
		translation: "ловить",
		difficulty: "medium",
		examples: [
			"I catch the ball",
			"He caught a cold",
			"We have caught the thief",
		],
	},
	{
		id: "v25",
		base: "choose",
		past: "chose",
		participle: "chosen",
		translation: "выбирать",
		difficulty: "medium",
		examples: [
			"I choose wisely",
			"She chose the red dress",
			"They have chosen a leader",
		],
	},
	{
		id: "v26",
		base: "draw",
		past: "drew",
		participle: "drawn",
		translation: "рисовать",
		difficulty: "rare",
		examples: ["I draw pictures", "He drew a map", "We have drawn conclusions"],
	},
	{
		id: "v27",
		base: "drink",
		past: "drank",
		participle: "drunk",
		translation: "пить",
		difficulty: "medium",
		examples: [
			"I drink water",
			"She drank coffee",
			"They have drunk all the juice",
		],
	},
	{
		id: "v28",
		base: "drive",
		past: "drove",
		participle: "driven",
		translation: "водить (машину)",
		difficulty: "medium",
		examples: [
			"I drive to work",
			"He drove carefully",
			"We have driven for hours",
		],
	},
	{
		id: "v29",
		base: "eat",
		past: "ate",
		participle: "eaten",
		translation: "есть",
		difficulty: "common",
		examples: ["I eat healthy", "She ate breakfast", "They have eaten already"],
	},
	{
		id: "v30",
		base: "fall",
		past: "fell",
		participle: "fallen",
		translation: "падать",
		difficulty: "medium",
		examples: ["I fall asleep", "He fell down", "We have fallen behind"],
	},
];

// Helper functions to get random words/verbs
export function getRandomWords(count: number): Word[] {
	const shuffled = [...SAMPLE_WORDS].sort(() => Math.random() - 0.5);
	return shuffled.slice(0, count);
}

export function getRandomVerbs(count: number): Verb[] {
	const shuffled = [...SAMPLE_VERBS].sort(() => Math.random() - 0.5);
	return shuffled.slice(0, count);
}

export function getRandomWrongAnswers(
	correctAnswer: string,
	allWords: Word[],
	count: number = 3,
): string[] {
	const wrongAnswers = allWords
		.filter((w) => w.translation !== correctAnswer)
		.map((w) => w.translation)
		.sort(() => Math.random() - 0.5)
		.slice(0, count);

	return wrongAnswers;
}
