/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MistakesRouteImport } from './routes/mistakes'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CustomWordsRouteImport } from './routes/custom-words'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnWordsRouteImport } from './routes/learn.words'
import { Route as LearnVerbsRouteImport } from './routes/learn.verbs'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MistakesRoute = MistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomWordsRoute = CustomWordsRouteImport.update({
  id: '/custom-words',
  path: '/custom-words',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnWordsRoute = LearnWordsRouteImport.update({
  id: '/learn/words',
  path: '/learn/words',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnVerbsRoute = LearnVerbsRouteImport.update({
  id: '/learn/verbs',
  path: '/learn/verbs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/custom-words': typeof CustomWordsRoute
  '/history': typeof HistoryRoute
  '/mistakes': typeof MistakesRoute
  '/profile': typeof ProfileRoute
  '/stats': typeof StatsRoute
  '/learn/verbs': typeof LearnVerbsRoute
  '/learn/words': typeof LearnWordsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/custom-words': typeof CustomWordsRoute
  '/history': typeof HistoryRoute
  '/mistakes': typeof MistakesRoute
  '/profile': typeof ProfileRoute
  '/stats': typeof StatsRoute
  '/learn/verbs': typeof LearnVerbsRoute
  '/learn/words': typeof LearnWordsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/custom-words': typeof CustomWordsRoute
  '/history': typeof HistoryRoute
  '/mistakes': typeof MistakesRoute
  '/profile': typeof ProfileRoute
  '/stats': typeof StatsRoute
  '/learn/verbs': typeof LearnVerbsRoute
  '/learn/words': typeof LearnWordsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/custom-words'
    | '/history'
    | '/mistakes'
    | '/profile'
    | '/stats'
    | '/learn/verbs'
    | '/learn/words'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/custom-words'
    | '/history'
    | '/mistakes'
    | '/profile'
    | '/stats'
    | '/learn/verbs'
    | '/learn/words'
  id:
    | '__root__'
    | '/'
    | '/custom-words'
    | '/history'
    | '/mistakes'
    | '/profile'
    | '/stats'
    | '/learn/verbs'
    | '/learn/words'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomWordsRoute: typeof CustomWordsRoute
  HistoryRoute: typeof HistoryRoute
  MistakesRoute: typeof MistakesRoute
  ProfileRoute: typeof ProfileRoute
  StatsRoute: typeof StatsRoute
  LearnVerbsRoute: typeof LearnVerbsRoute
  LearnWordsRoute: typeof LearnWordsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mistakes': {
      id: '/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof MistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-words': {
      id: '/custom-words'
      path: '/custom-words'
      fullPath: '/custom-words'
      preLoaderRoute: typeof CustomWordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/words': {
      id: '/learn/words'
      path: '/learn/words'
      fullPath: '/learn/words'
      preLoaderRoute: typeof LearnWordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/verbs': {
      id: '/learn/verbs'
      path: '/learn/verbs'
      fullPath: '/learn/verbs'
      preLoaderRoute: typeof LearnVerbsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomWordsRoute: CustomWordsRoute,
  HistoryRoute: HistoryRoute,
  MistakesRoute: MistakesRoute,
  ProfileRoute: ProfileRoute,
  StatsRoute: StatsRoute,
  LearnVerbsRoute: LearnVerbsRoute,
  LearnWordsRoute: LearnWordsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
